### ISSUE TITLE
Claiming legitimate relationship to access record detail

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#1]
As a user, when I return my search results, I need the ability to self claim I have a legitimate relationship with the patient, before I access the details within the patient record.

This self claim must be audited

**Comment by PhilBarrett** [comment]
Reusing showcase Legitimate Relationship modal

**Comment by tony-shannon** [comment]
see Showcase for example

**Comment by PhilBarrett** [comment]
![selfclaimlr](https://user-images.githubusercontent.com/12699244/53818659-57905d80-3f60-11e9-8d3f-17b474a0deb1.png)

**Comment by PhilBarrett** [comment]
Descoped for the moment as no clear wording agreed
