### ISSUE TITLE
MPV address isn't displaying correctly

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#100]
when creating a new patient, the full address isn't show in the MPV list. 

![Screen Shot 2019-04-30 at 12.11.16.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/c2456753-6543-423f-a7c2-8313c9c2193f)![Screen Shot 2019-04-30 at 12.14.29.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/c0f5eb76-3257-4935-aab4-0ff7b6aef09a)

When refreshed it appears, but postcode doesn't appear. ![Screen Shot 2019-04-30 at 12.39.06.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/b7cd5758-8112-4e44-98d1-6ea384615055)

**Comment by PhilBarrett** [comment]
Should display

Address line 1
City
County/District
Postcode

Currently shows
Address line 1
County/District
City
Country

**Comment by kuvakina** [comment]
@BogdanScherban here is a video: https://drive.google.com/file/d/140a83qtLoSxp2-87CXY5uZSmkgmz5Qid/view

**Comment by kuvakina** [comment]
@PhilBarrett this issue was fixed:
![44444.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/c7c48a6a-4d41-44fe-9975-eecd8aa40489)

**Comment by PhilBarrett** [comment]
Reviewed and working fine, thank you
