### ISSUE TITLE
Section 7 bugs

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#101]
"Hello Ian I found one strange thing regarding step #7, when we sending array of clinician_signatures, ethercis saves only first item and skip other data. But in step #8 and #9 everything works fine. I can show you data that I am sending if it will help

https://gist.github.com/DmitrySolyannik/469d2b76d9e1819e4aa4c7eccf81e55a

And this one more detailed 
https://gist.githubusercontent.com/DmitrySolyannik/eb5902dc7d1c159990725b6d3fc2b22e/raw/d25b37f54355483c176628bd62f4c418e5683b0d/respect_update_detail.json"

Also Section & isn't recording Senior Responsible Clinician to be displayed in PDF

**Comment by DmitrySolyannik** [comment]
@tony-shannon , @PhilBarrett 
Added changes to this issue, added ability to send and output data for step #7
https://github.com/QEWD-Courier/QEWD-Courier/pull/74

**Comment by tony-shannon** [comment]
awaiting PR review by Alexey

**Comment by kuvakina** [comment]
@PhilBarrett @tony-shannon 
Except for "Section 7 isn't recording Senior Responsible Clinician", we fixed the saving of all arrays in Section 7 for both Version and PDF :
![aa2.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/8a04a87f-22c5-4da2-b372-d8e11eef56af)
![aa3.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/373f5fb7-3980-4cd3-b63c-d1e2a5d7ea3f)

**Comment by tony-shannon** [comment]
PR reviewed by Alexey and merged
Section 7 needs retesting please

**Comment by PhilBarrett** [comment]
@simongamester can I ask for your help regarding @kuvakina 's update please and "Except for "Section 7 isn't recording Senior Responsible Clinician", we fixed the saving of all arrays in Section 7 for both Version and PDF ":

**Comment by simongamester** [comment]
@tony-shannon How does the system identify a clinician as a senior clinician. Could you send me an example of the json data?

I can see the output from @PhilBarrett 's earlier post, that the output below that there doesn't appear to be a flag to identify the clinician's signature.

https://gist.githubusercontent.com/DmitrySolyannik/eb5902dc7d1c159990725b6d3fc2b22e/raw/d25b37f54355483c176628bd62f4c418e5683b0d/respect_update_detail.json

I refer to all lines stating ''nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:'

**Comment by PhilBarrett** [comment]
@BogdanScherban @DmitrySolyannik can you put your heads together on where Senior Responsible Clinician data field is coming from in EtherCIS, is handled in QEWD and is presented in PulseTile, so the PDF kit can pick it up properly. 

Please can you update in here with your findings on what needs to be done, thanks

**Comment by kuvakina** [comment]
We asked Ian's help:

**Dmitry** :
Hello @Ian, could you please point me about one thing on step #7 (respectforms), we can choose senior responsible clinician by checkbox (PulseTile side), But I don't see any information about this field in NSS_RESPECT documentation. It should be in array 
nss_respect_form/respect_headings/a7._clinician_signatures/service:0

https://raw.githubusercontent.com/RippleOSI/Ripple-openEHR/master/docs/bindings/Current%20Ripple%20Headings/NSS%20ReSPECT/NSS_RESPECT.md

**Ian** :
Hi 

// 7.Clinician Signatures
    // Valueset:
    // ReSPECT clinician signature
    //ReSPECT Senior Responsible Clinician signature

Set the value of 

  "nss_respect_form/respect_headings/a7._clinician_signatures/service:0/service_name": "ReSPECT clinician signature",

to one of these 2 text values

**Dmitry** :
So, for example If I have 5 clinician signatures and 2 of them are senior I should add 
 "nss_respect_form/respect_headings/a7._clinician_signatures/service:0/service_name": "ReSPECT clinician signature",
 "nss_respect_form/respect_headings/a7._clinician_signatures/service:1/service_name": "ReSPECT clinician signature",

and other three should be without this text ?

**Ian** :
No ! :)

Senior clinicans should be 

"nss_respect_form/respect_headings/a7._clinician_signatures/service:0/service_name": "ReSPECT Senior Responsible Clinician signature",

Others should be

"nss_respect_form/respect_headings/a7._clinician_signatures/service:0/service_name": "ReSPECT clinician signature",

**Comment by kuvakina** [comment]
Dima added changes, and now we can save "Senior responsible clinician" :
![ww4.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/49e523c6-2a5c-41e6-b7ab-9818ed3fb22a)

**Comment by PhilBarrett** [comment]
Reviewed and closing
