### ISSUE TITLE
MPI to cater for preferred name status

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#102]

**Comment by PhilBarrett** [comment]
We need to understand if the FHIR MPI can be altered so preferred name is used in place of prefix
or added as an additional value

UI shouldn't send back null value as this will result in the following error

{error: "instance.name[0].prefix: is not of a type(s) string", path: "/mpi/Patient/:id"}
error: "instance.name[0].prefix: is not of a type(s) string"
path: "/mpi/Patient/:id"

**Comment by tony-shannon** [comment]
see this added detail on the name type in FHIR Patient profile
from here
https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-Patient-1

![image.png](https://images.zenhubusercontent.com/5c8be461fd0adb6f09c83d64/5399f95e-7175-4ea1-a1ea-33afd4438dff)

ie we need to accomodate an array with 2 names
#1 official inc prefix
#2 usual aka preferred name 

as far as I can tell the json schema Rob has chosen to include shouldnt preclude that
https://github.com/QEWD-Courier/fhir-mpi/blob/master/schema/patient.json

**Comment by tony-shannon** [comment]
see example data from ian McN which may help to test 

https://gist.github.com/freshehr/6090ee5e367d64052c3078a98fdb9eac

**Comment by kuvakina** [comment]
For this task, Dima has to add validation and Bogdan also has to add the field.

**Comment by kuvakina** [comment]
Dima and Bogdan made Preferred Name as an optional field (Dima added validation, and Bogdan changes JSON structure that client sends on server):
![aa4.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/a8e6d831-7d4e-4744-8216-02acedca3deb)

**Comment by PhilBarrett** [comment]
Working as intended

Shows in the table the Name column should display as concatenated 

First name
Last name

Preferred name is optional and not displayed in the Name column

**Comment by PhilBarrett** [comment]
Resolved, closing out
