### ISSUE TITLE
Section 9: Shows Clinical rather than Clinician (see screenshot)

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#103]
![Screen Shot 2019-05-02 at 10.29.06.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/6e043e3c-0096-48e8-bbb3-94edca5f78e1)

**Comment by PhilBarrett** [comment]
For Clinician Name and Clinician Signature

**Comment by kuvakina** [comment]
@PhilBarrett this issue was fixed:
![555.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/05c15e2f-edc5-4cc5-961a-bae5cb422589)

**Comment by PhilBarrett** [comment]
@kuvakina can you explain the dependency here please?

**Comment by PhilBarrett** [comment]
Reviewed and closing
