### ISSUE TITLE
Timeout issue when creating first ReSPECT form

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#105]
When creating a new respect form for the first time, we know that ethercis creates version one (as the Post) and version two is the GET and update. See #91

In Nes-Demo, when I create a new respect form and complete the sections, it times me out and I need to re-login. When i go back in, version 1 is there and allows me to then UPDATE in a new version. 

This is at odds with creating a new version for the first time and 2 versions appearing which can be easily explained and something has changed overnight that is causing this and the timeout

**Comment by DmitrySolyannik** [comment]
@PhilBarrett , @tony-shannon 
I've fixed this issue and increase session time from 2 minutes to 1 hour

**Comment by tony-shannon** [comment]
thanks Dima, will test soon

**Comment by PhilBarrett** [comment]
Working fine, thank you
