### ISSUE TITLE
Respect form - Jitter Bug - on adjusting page height

### ISSUE THREAD

**Issue by tony-shannon** [RippleOSI/NHS_Ed_Scotland_Open_Platform#106]
see video attached from AH

**Comment by tony-shannon** [comment]
see this link to video
https://youtu.be/13d9xmM0otY

with comment from AH

"I'm guessing the root cause is some JS/CSS setting the width of the page, the scroll bars being created, they change the width of the page, so the code changes the width of the page again. correction: height of the pageOne of the tricks to triggering it is to scroll down the page (with mouse wheel or keyboard)"

**Comment by kuvakina** [comment]
@tony-shannon sorry, we don't have access to the video. Is this issue for Bogdan?

**Comment by PhilBarrett** [comment]
I've not been able to recreate after many attempts. will leave here

**Comment by ChikongCham** [comment]
Search for 'test' and on retrieval of patient list, use mouse scroll wheel to scroll down the page.  It appears that the page is rapidly alternating between showing and hiding the vertical scroll bar on the right of the page.

**Comment by PhilBarrett** [comment]
https://drive.google.com/file/d/1r7X9Vx5HcqHQl9FphRxyG33w-CH_i4OK/view also on showcase 0:11

**Comment by kuvakina** [comment]
@PhilBarrett @ChikongCham we fixed the issue, could you please check it?

**Comment by tony-shannon** [comment]
please confirm this change has been pushed to all relevant branches @BogdanScherban

**Comment by BogdanScherban** [comment]
@tony-shannon 

I checked that problem with flicking isn't presented more (nes-dev):
https://drive.google.com/file/d/183_XZRAxX61I8lIPsLfd8uAp8VcBGUIB/view

Changes for this bug fixing was uploaded to all our branches.

**Comment by PhilBarrett** [comment]
Please can this be pushed to nes-demo @BogdanScherban

**Comment by BogdanScherban** [comment]
@PhilBarrett 

Sorry, but I don't know, how to update nes-demo. I can update only nes-dev.
I can prepare build for @DmitrySolyannik and he will upload it tomorrow.

**Comment by ChikongCham** [comment]
I confirm jitter bug on nes-demo has been resolved.  Vertical scrollbar now appears only when window content requires it and not present on full-screen. Many thanks.

**Comment by PhilBarrett** [comment]
Thanks for confirming @ChikongCham
