### ISSUE TITLE
Check paginator on Patients List (Seems it shows only 10 users per page, and hide others)

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#109]

**Comment by kuvakina** [comment]
@PhilBarrett Issue with pages was fixed:
![aa1.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/38474803-6df3-4556-869d-8737da0e2052)
![aa0.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/d69eddc0-35f7-487e-bd9f-cbddcd5a5fb4)

**Comment by PhilBarrett** [comment]
Reviewed and working fine. thank you
