### ISSUE TITLE
Landing page feedback

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#11]
- [x] Replace existing NES logo with NHS Scotland
- [x] Remove copyright notice at bottom of screen and Ripple Foundation logo

**Comment by PhilBarrett** [comment]
Can still see these,  in top banner and at footer, sorry

**Comment by simongamester** [comment]
Some slides weren't synced to InVision. Can you take another look?

**Comment by PhilBarrett** [comment]
Bottom bit is fine, Top next to the back button just needs changing to NHS Scotland throughout
