### ISSUE TITLE
PDF not opens for some ReSPECT versions

### ISSUE THREAD

**Issue by kuvakina** [RippleOSI/NHS_Ed_Scotland_Open_Platform#111]
We noticed, that we can't open PDF form after ~4 version.

**Comment by BogdanScherban** [comment]
I've found a reason and solved the issue. 

There were two reasons:
1) Error in function, which parsed JSON with ReSPECT version data;
2) Number data in JS should be convert to string (if we want to add it to PDF kit)

**Comment by kuvakina** [comment]
@PhilBarrett Bogdan fixed this one. Above Bogdan mentioned the reason for the bug

**Comment by PhilBarrett** [comment]
Can't reproduce, so closing now fixed
