### ISSUE TITLE
Need to highlight chosen issues

### ISSUE THREAD

**Issue by kuvakina** [RippleOSI/NHS_Ed_Scotland_Open_Platform#113]
Right now when you click on issue and redirect on issue page, it not clear what issue you chose. Need to highlight chosen issues:

**Helm-RA** :
![qq4.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/99c83df6-a9f0-4215-9869-8daf1019af14)

**OneLondon** :
![qq5.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/66ff3b8a-f3a7-445c-830e-6aaf9edbf40b)

**Comment by BogdanScherban** [comment]
@fzaninotto 
Francois, I need in your help in this issue. 

1) What I want to do.

We have a table, which is created by Datagrid. I want to set backgroundColor (main theme color) and color (white, for text) to the row, which is opened now.

2) How I tried to do this.

I used Datagrid attribute rowStyle according to https://marmelab.com/react-admin/List.html#row-style-function:
```
class ListTemplate extends Component {

    .....
    
    setRowStyle = (record, index) => {
        const { location, contrastMode } = this.props;
        const pathname = get(location, 'pathname', null);
        const pathnameArray = pathname.split('/');
        const sourceId = get(pathnameArray, [2], null);
        let result = {};

        // Check, is current row opened now?
        if (sourceId === record.id) {
            result =  {
                backgroundColor: contrastMode ? window.config.darkPalette.mainColor : window.config.lightPalette.mainColor,
                color: "#fff",
            }
        }
        return result;
    };
 
    .......

    render() {

        return(
           
              <Datagrid rowStyle={this.setRowStyle} className={classes.tableList} rowClick="edit">
                   {children}
              </Datagrid>

        );

     }
}

```

But unfortunastely, as result this way gives possibility only to set backgroundColor. I can't set color of text - it is black:
![Screenshot from 2019-05-17 18-39-16.png](https://images.zenhubusercontent.com/5cd92c639c62ea1ca66b24a2/a6944ab8-b003-44ad-bfa2-7a9a28be73e6)

I tried to set color by:
```
{
     color: "#fff !important"
}
or
{
     '& td p ': {
          color: "#fff"
     }
}
```

But in all cases I can set only inline styles of the tr tag.

3) Could you please give me an advice: 
- how to set text color in this case?
- how to pass theme params to the function setRowStyle() and don't use window.config ?

**Comment by PhilBarrett** [comment]
@kuvakina please can this info be copied over and a new issue created under PulseTile-RA.

Wrong repo I'm afraid.

**Comment by kuvakina** [comment]
@PhilBarrett sorry, will change in a mo

Moved here: https://app.zenhub.com/workspaces/ripple-combined-project-space-5c8be494fd0adb6f09c83d6b/issues/pulsetile/pulsetile-ra/91

**Comment by tony-shannon** [comment]
Closing this issue as related issue is here
https://github.com/PulseTile/PulseTile-RA/issues/91
