### ISSUE TITLE
Add validation for required fields

### ISSUE THREAD

**Issue by kuvakina** [RippleOSI/NHS_Ed_Scotland_Open_Platform#116]
Right now if you missed the field, you just see Something is wrong error and nothing else. We should add validation, so user will see in which field the problem

**Comment by PhilBarrett** [comment]
We need to understand which fields are mandatory to create a new patient record and also the validation rules before making the changes please.

**Comment by kuvakina** [comment]
@PhilBarrett when creating new patient all fields required, except for Preferred name.

**Comment by kuvakina** [comment]
@PhilBarrett this is done for NES:
![Screenshot from 2019-05-23 17-10-38.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/23e37010-2ccd-4517-a6a4-ca1e8f17b2c5)
