### ISSUE TITLE
Single Patient View Changes

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#14]
#### Removals / amends
- [x] In the patient banner remove GP, only display basic demographic information
- [x] Remove 'sort' function from Respect form table as defunct
- [x] Spell check / typos on mockups
- [x] ReSPECT slider to mimic the form rather than flat slider
- [x] Emphasis of CPR choices (embolden)
- [x] Section 6 as Scottish project, change order to Scottish first 
- [x] maximise /minimise toggle on summary and detail panels

#### New requirements
- [x] Ability to print out form
- [x] Version control
- [x] Date / Time control with calendar function included for all date fields 
- [x]  Calculate age
- [ ] Considering multipart form

**Comment by PhilBarrett** [comment]
Out of Scope for first phase

- [ ] Preventing multiple access to a ReSPECT form at the same time (lock)
- [ ] Hover/help text per field/header to guide the user

**Comment by simongamester** [comment]
@PhilBarrett @tony-shannon Re: "ReSPECT slider to mimic the form rather than flat slider" how would you recommend we change this. Does this apply to the slider in section 3, 4, or both?

**Comment by PhilBarrett** [comment]
If there isn't one readily available, I think we are going to have to say that's additional work which will need to be picked up separately. Unless they can provide one.

**Comment by simongamester** [comment]
Thanks @PhilBarrett Can you point out typos anywhere? Also, not sure what's required for the calendar box item? All dates have a calendar button / icon which will toggle a calendar when clicked. Anywhere this is missing?

**Comment by PhilBarrett** [comment]
- [x] ReSPECT description - situations is missing the s
- [x] Section 5 - 2nd question, Spelling and grammar. attorney and responsibility
- [x] Section 6 - A spelling of Mental, Friends

- [x] Date completed, including time - can see the calendar, sorry


Re the slider, perhaps we could simply just add the image and put the slider underneath it, so it's clear what they are sliding for? WDYT @tony-shannon ?
![Screen Shot 2019-02-28 at 11.58.29.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216456fb6b7191a379ee0c2e59415d47be5d4a1f06a3a3dc78e2a436628f0f0ee5d53f5c7d903d17ffed801fba54bf728c198cb7be9850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecd59f54ee44951a4103661f43b.png)
![Screen Shot 2019-02-28 at 12.00.13.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216456fb6b7191a379ed0c2b51415e4dbe5d4a1f06a3a3dc78e2a436628f0f0ee5d53f5c7d903d17ffed801fba54bf728c198cb7be9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecd59f54ee44951a4113e61f43b.png)
