### ISSUE TITLE
ReSPECT Data Set on multiform sections

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#17]
- [ ] Mandatory fields
- [ ] Partial, incomplete, publish states
- [ ] The ability to save section and revisit
- [ ] Consider the value of date on summary table
- [ ] Constraining character limits, especially if enabling print outs
- [ ] Respect form Authorship by section? 1 or many?

**Comment by tony-shannon** [comment]
re Authorship- options
1) only one user per form - assume auth details come  from oauth soln
2) allow 2+ users per form-  assume auth details come  from oauth soln - ? lock versions to avoid duplicate entry or alert to UI "being edited at this time"
could end with sections 1,3,5 by author A and 2,4, 6 from author B
Would need guidance/help text
