### ISSUE TITLE
Authorship UX/UI Feedback

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#22]
Rules around authorship/ validity 
It was agreed that
- [x] Mandatory fields are reviewed and completed at the UI level
- [ ] Section 4 , 6 are mandatory before a form can be created / updated
- [x] for new form recommend complete form and responsibility all form with - warning flag ( please ensure you completed section 4 and 6)

**Comment by tony-shannon** [comment]
sections 4 date completed should be enabled

**Comment by kuvakina** [comment]
Related to issues #31 and #33

**Comment by BogdanScherban** [comment]
@PhilBarrett @tony-shannon 

This was done:
> for new form recommend complete form and responsibility all form with - warning flag ( please ensure you completed section 4 and 6)

This issue will be done tomorrow, when we create one general button to update version (Publish):
> Section 4 , 6 are mandatory before a form can be created / updated

**Comment by PhilBarrett** [comment]
See #66 for required behaviour, closing out here
