### ISSUE TITLE
ReSPECT Form - section 1

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#28]
As per 

https://projects.invisionapp.com/share/DAQQSTW9WVM#/screens/349299441

https://projects.invisionapp.com/share/DAQQSTW9WVM#/screens/349299439

**Comment by BogdanScherban** [comment]
This section has been done:
1) all required elements are presents;
2) action/reducer/sagas for creating API-request has been created

Some styles fixing are required, but it can be done later

![image](https://user-images.githubusercontent.com/39263134/53742251-e178f180-3ea0-11e9-814d-8150bcfca4c0.png)

**Comment by kuvakina** [comment]
For this and other sections, there are left some work to do, and for this section too:

1. add icon Print
2. add icon History (just one question: we have to add it everywhere, like on mockups, or only on a new page?)
3. should we add Expand button to details block?
4. do we nee X button on details block, if we have Cancel button?
5. to fix styles
6. rename Complete button to Finish

**Comment by PhilBarrett** [comment]
@simongamester can you advise on these points please

**Comment by simongamester** [comment]
Hi @kuvakina 

2. This should appear within the header for the ReSPECT Sections table throughout the system. This takes the user back to the Versions table where they can review other versions of the form.

3. Yes, the expand button should be used on all detail blocks and a full width view of this should be available. 

4. Yes, suggest we use both X and cancel buttons, although they perform the same function for now.

Thanks,

Simon

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett 
This section is ready. All fields are presented, styles are similar to mockup.

![image](https://user-images.githubusercontent.com/39263134/53972278-2605c680-4107-11e9-850f-2c96148e0a94.png)

But now this section works without server side. Data are saved only in React Store.
The next step of this issue should be adding the possibility work with server side.

**Comment by BogdanScherban** [comment]
@PhilBarrett @tony-shannon 

Only one question: which countries should be in Country field? In mockup this field is selectbox:
![image](https://user-images.githubusercontent.com/39263134/53972596-c52abe00-4107-11e9-98a3-01c25f2c3722.png)

Or should I left this field as simple text input?

**Comment by PhilBarrett** [comment]
Just as per the mockup with UK as the default for now. We can add other countries at another stage, but with it being for the UK, I'm not sure needed.

**Comment by tony-shannon** [comment]
need to check that all demographics are imported from demographics API ok

**Comment by kuvakina** [comment]
For Section 1:
![2019-04-15_1757](https://user-images.githubusercontent.com/40596171/56142922-303d9f00-5fa8-11e9-95e3-2808e1a0fe79.png)

- [x] 1. Hide Date Completed
- [x] 2. Hide System Information

**Comment by kuvakina** [comment]
This task is Done:
![1n](https://user-images.githubusercontent.com/40596171/56197147-e1901380-6040-11e9-84ba-6ab64e3f5eb1.png)

**Comment by PhilBarrett** [comment]
Thanks, closing issue off
