### ISSUE TITLE
ReSPECT Form Section 2

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#29]
See 
https://projects.invisionapp.com/share/DAQQSTW9WVM#/screens/349299442

**Comment by BogdanScherban** [comment]
This section has been done:
1) all required form elements are presented
2) action/reducer/sagas are created

Styles fixing can be done later.

![image](https://user-images.githubusercontent.com/39263134/53742349-1ab16180-3ea1-11e9-9d88-09915e29d20e.png)

**Comment by kuvakina** [comment]
For this and other sections, there are left some work to do, and for this section too:

1. add icon Print
2. add icon History (just one question: we have to add it everywhere, like on mockups, or only on a new page?)
3. should we add Expand button to details block?
4. do we nee X button on details block, if we have Cancel button?
5. to fix styles
6. rename Complete button to Finish

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett
This section is ready. All fields are presented, styles are similar to mockup.

![image](https://user-images.githubusercontent.com/39263134/53972683-f4412f80-4107-11e9-9390-55d400e54cd2.png)

But now this section works without server side. Data are saved only in React Store.
The next step of this issue should be adding the possibility work with server side.

**Comment by tony-shannon** [comment]
remove data completed in detail here

**Comment by kuvakina** [comment]
For Section 2:
![2019-04-15_1801](https://user-images.githubusercontent.com/40596171/56143125-a0e4bb80-5fa8-11e9-90ac-a50e32d6735c.png)


- [x] 1. Hide Date Completed
- [x] 2. Hide System Information

**Comment by kuvakina** [comment]
This task is Done:
![2n](https://user-images.githubusercontent.com/40596171/56197987-a5f64900-6042-11e9-8ebb-de9962389a64.png)

**Comment by PhilBarrett** [comment]
Thanks
