### ISSUE TITLE
ReSPECT form Section 3

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#30]
https://projects.invisionapp.com/share/DAQQSTW9WVM#/screens/349299443

**Comment by kuvakina** [comment]
For this and other sections, there are left some work to do, and for this section too:

1. add icon Print
2. add icon History (just one question: we have to add it everywhere, like on mockups, or only on a new page?)
3. should we add Expand button to details block?
4. do we nee X button on details block, if we have Cancel button?
5. to fix styles
6. rename Complete button to Finish

Also concrete for this section:
7. add Range. And here we wanted to ask you, @tony-shannon  and @PhilBarrett , the separator in Range on mockups looks like this - / (https://www.screencast.com/t/yUAsuAb1p), can we for nor make it look like this - | (vertical separator)?

**Comment by PhilBarrett** [comment]
@kuvakina needs to be as per https://www.respectprocess.org.uk/_pdfs/ReSPECT-Specimen-Form.pdf so a vertical won't work I'm afraid.

**Comment by kuvakina** [comment]
> @kuvakina needs to be as per https://www.respectprocess.org.uk/_pdfs/ReSPECT-Specimen-Form.pdf so a vertical won't work I'm afraid.

ok, thanks. I think @BogdanScherban have found a way already make it as on mockups

**Comment by BogdanScherban** [comment]
Range has been added:
![RANGE.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb3796441a5980011efd33d/125516c66e82c728ace21e0d46dab5b404a7c1e5cdf9ad4cae58f3806b1c65262b05a02e23d0e57fbd417a540b5f4ea5420d5647a9af8c39baa47e21d40854b088270a36d43703adb0881eba04bb27834e83b1bd8e45c8fa70.png)

Other notes (1-5) will be added later, when we will fix styles.

**Comment by PhilBarrett** [comment]
Thanks Bogdan - could the slider go across the full width of the scale
please.

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett
This section is ready. All fields are presented, styles are similar to mockup.

![image](https://user-images.githubusercontent.com/39263134/53972773-18047580-4108-11e9-8e9e-afa8cfe4d3fc.png)

But now this section works without server side. Data are saved only in React Store.
The next step of this issue should be adding the possibility work with server side.

**Comment by tony-shannon** [comment]
need to test JSON here for persistence

**Comment by kuvakina** [comment]
For Section 3:
![3](https://user-images.githubusercontent.com/40596171/56143320-fd47db00-5fa8-11e9-9110-24ce2bef1ad8.png)

- [x] 1. Hide Date Completed
- [x] 2. Hide System Information

**Comment by kuvakina** [comment]
This task is Done:
![3n](https://user-images.githubusercontent.com/40596171/56198057-caeabc00-6042-11e9-8667-24a5592cf204.png)
