### ISSUE TITLE
ReSPECT form - Printing / PDF Kit

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#39]
https://projects.invisionapp.com/share/DAQQSTW9WVM#/screens/349326737

https://projects.invisionapp.com/share/DAQQSTW9WVM#/screens/349326738

**Comment by PhilBarrett** [comment]
PDFs without watermarks provided by Juliet today, contact being made with Ivor and Matt from Helix who did the design for the  original ReSPECT form around receiving the original files/ art files. https://drive.google.com/drive/u/0/folders/1G67vqfLKjNvmwJQsiAVLrXyeFjUADRf_

**Comment by simongamester** [comment]
@PhilBarrett Could you send me an invite to this google drive folder please?

**Comment by PhilBarrett** [comment]
Should be with you now @simongamester

**Comment by PhilBarrett** [comment]
@simongamester Do you have any update on this please now you have the forms?

**Comment by simongamester** [comment]
I've created a static version of this which wrapped within Browserify. This creates a page PDF document, importing the ReSPECT form as images, then overlaying each field over the top: 

I've included this in the following repo, with a brief explanation of the code:

https://github.com/simongamester/pdfkit/tree/master/demo

**Comment by tony-shannon** [comment]
Hi Simon 
Can you replace the JSON you have crafted for this with that already in use by PulseTile please?
See doc here
https://docs.google.com/document/u/1/d/1MhA7-kCCcUM2kBKb6RmsAocV1vRH2DgYNF50O-fNewg/edit
We needed to fix the UI JSON for mapping to the openEHR template.
Hope will be easy enough for you to do so
thanks
Tony

**Comment by tony-shannon** [comment]
see this in action here.. 
http://wrathful-request.surge.sh/browser.html

![image](https://user-images.githubusercontent.com/939996/54835828-dbfe1280-4cba-11e9-9668-36b283a84c77.png)

**Comment by tony-shannon** [comment]
@simongamester could you please update this with a brief screencast to allow @BogdanScherban to see how this can be migrated into REspect form application, thanks

**Comment by simongamester** [comment]
Here's the screencast: https://www.dropbox.com/s/wc0vdm9h9daa3im/ReSPECT%20PDF%20Kit%20Walkthrough.mov?dl=0

And the readme to the repo's demo folder: https://github.com/simongamester/pdfkit/tree/master/demo
