### ISSUE TITLE
QEWD-Courier - FHIR MPI microservice

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#40]
This piece of work needs to be hooked up to the MPV view of PT and allow for adding a new patient. Also needs to be connected to QEWD Yotta Db for patients for persistence and the data format, aligned with CareConnect JSON format.

**Comment by PhilBarrett** [comment]
https://nhsconnect.github.io/CareConnectAPI/api_entity_patient.html

**Comment by kuvakina** [comment]
I think we need more details and probably Dima'd needed Rob's advises regarding this issue

**Comment by tony-shannon** [comment]
Rob has done ground work on this, as has Rich so this can be tested shortly

**Comment by tony-shannon** [comment]
FHIR JSON example as provided by RobT

{
"name": {
"family": "Chalmers",
"given": [
"Peter",
"James"
],
"prefix": "Mr"
},
"telecom": "07700 900000",
"gender": "male",
"birthDate": "1974-12-25",
"address": {
"line": "26, High Street",
"city": "Dundee",
"district": "Tayside",
"postalCode": "DU2 3SK",
"country": "United Kingdom"
}
}

**Comment by tony-shannon** [comment]
Set up of Rob Tweeds quick FHIR MPI version is all documented here: https://github.com/robtweed/fhir-mpi
Documentation due for furtther update soon

**Comment by tony-shannon** [comment]
seems to be working well
