### ISSUE TITLE
ReSPECT form API to OpenEHR inc version control

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#41]

**Comment by kuvakina** [comment]
@PhilBarrett I'm afraid I'd need details to what I should do here

**Comment by PhilBarrett** [comment]
Awaiting the APIs from @freshehr which will be ready for Monday

**Comment by kuvakina** [comment]
@PhilBarrett understand, thanks

**Comment by PhilBarrett** [comment]
https://github.com/RippleOSI/Ripple-openEHR/tree/master/docs/bindings/Current%20Ripple%20Headings/NSS%20ReSPECT

Guidance document and sample instance composition

The operational template is at 

https://github.com/RippleOSI/Ripple-openEHR/blob/master/technical/operational/RESPECT_NSS-v0.opt

@kuvakina this in from Ian

**Comment by tony-shannon** [comment]
we have set up a dev box ethercis1.3-test in our DO env which can be used for this 

need to update our Docker containers for EtherCIS 1.3 version, as the initial deployment will be to docker based env
https://github.com/RippleOSI/ethercis-server-docker
https://github.com/RippleOSI/ethercis-database-docker
.. this update should include some test data loading for dev purposes

we will  need to load the latest  Respect template in the etherCIS1.3 test env also

**Comment by chevalleyc** [comment]
Related with ethercis CR #157. AFAIK querying on composition state (complete, uncomplete etc.) is not required.

**Comment by tony-shannon** [comment]
Please see this Respect form version control #8 for more related discussion

**Comment by PhilBarrett** [comment]
closing as  #8 now master
