### ISSUE TITLE
Add ReSPECT  logos, in place of text ReSPECT & add NHS Scotland logo

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#44]
See https://drive.google.com/drive/folders/1G67vqfLKjNvmwJQsiAVLrXyeFjUADRf_?usp=sharing for file formats

@simongamester can you confirm which logo and placement on the designs please?

**Comment by PhilBarrett** [comment]
@kuvakina Simon has updated the wireframes

https://projects.invisionapp.com/share/DAQQSTW9WVM#/screens/349299438

**Comment by simongamester** [comment]
Please find enclosed the Respect Logo in 1x and 2x. Recommend 1x only if you're not adding in support for retina displays.
![ReSPECT+summary@2x.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb37967f01e4d00110fba95/125516c66e82c728ace21e0d46da91a913a7a09dc4faaa4ea95ce28d09143f316546b3397f8fe62bab0021435a0d1fff145b5a12fbabda7aa3e23c70835f5ee4d2380971d42103eee9dc4be05ce36ade0d97bcae884dcae93820e58f8746371d061989f74f78.png)
![ReSPECT+summary.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb37967f01e4d00110fba95/125516c66e82c728ace21e0d46da91a913a7a09dc4faaa4ea95ce28d6b0a65633b0ba92e7391a172fd1779000c0a4da9175f0d17adfcdd2ba6bf3f25835f5ebbd47f4366846c4ff8e7df46f554f832815d84b1b68b49c5ea392dee828c4c3e18040ac4.png)

**Comment by simongamester** [comment]
NHS Logo as used within the header. In 1x and 2x once again.
![1920px-NHS_Scotland.svg.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb37967f01e4d00110fba95/125516c66e82c728ace21e0d46b9cdc873929be4a1c18c7c975eff80254729776717b52c32c9a138ad4d71040c1b5ca6535d0d15afac8a2ef0b16e23db595fedd1645c21cf3e44fabd9003ad43eb7edf10d8eff6df0ed2e22f27e6818e4a3b1c011189ff5432a2994fda15.png)
![1920px-NHS_Scotland.svg@2x.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb37967f01e4d00110fba95/125516c66e82c728ace21e0d46b9cdc873929be4a1c18c7c975eff80254729776717b52c50d7fb6af3006b1300051bff054a5556f9abd878f3b539268d0e58bcd4395f74cf3e44a5bbd749ba13a632c91edbe2e3d7158abd7f37ed998e48341f001d8bfb5435a0904cca58f059ac.png)

**Comment by BogdanScherban** [comment]
This issue has been done:
![image](https://user-images.githubusercontent.com/39263134/54362154-1d664080-4671-11e9-9ccf-9e84cc627d79.png)
