### ISSUE TITLE
NES - ReSPECT UX/UI Refinements - High priorities

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#47]
see

https://docs.google.com/document/d/1E5-vaRo6b5-E3lkBZIhEZQCP0fYIkLVBi8meNbQ2zrQ/edit

**Comment by PhilBarrett** [comment]
Summary below:

- [x]  Brand navy blue colour does not match those from the wireframes. Change all uses of this colour to the one in the design including backgrounds and text colours.

Current colour: #000080
Design colour: #0078C8

- [x]  Apply HK Grotesk font for all text. Suggest applying to Body and * elements as the default rule. We used this on the old version of Helm, which I inlined within the css theme (for easy reference).

body, * {
	font-family: HK Grotesk;
}


 - [x] HIGH: Hovering over a clickable table row should change the cursor to pointer:
	
:hover {
cursor: pointer;
}

 - [x] HIGH: Pagination navigation should be separate from table and next / previous buttons should be the same height as the page numbers.

 - [x] HIGH: Clicking a column heading does not re-order the table.

 -  [x] HIGH: Within the designs, clicking on a patient record pulls up a side panel showing the patient’s information. It doesn’t direct the user to the Patient Summary directly.


 - [x] HIGH: Add a ‘View’ column to the table, which launches the users into the patient summary screen. Clicking any other part of the row pulls up the side panel.

- [x]  HIGH: The patient summary tab should be blank in MPV view (no labels)

- [x]  HIGH: The font size for input and textarea elements with the forms appears to be too small. Would recommend

font-size: 14px;

- [x]  HIGH: Clicking the cog next to Home displays the modal ok, however there’s no close icon within the modal. There should be an X to the top right.

**Comment by BogdanScherban** [comment]
@tony-shannon @PhilBarrett @simongamester 
**These issues has been done.** Builds with changes were uploaded to Showcase, Helm and Scotland:
- Brand navy blue colour does not match those from the wireframes. Change all uses of this colour to the one in the design including backgrounds and text colours.
- Apply HK Grotesk font for all text. Suggest applying to Body and * elements as the default rule. We used this on the old version of Helm, which I inlined within the css theme (for easy reference).
- HIGH: Hovering over a clickable table row should change the cursor to pointer:
- HIGH: Pagination navigation should be separate from table and next / previous buttons should be the same height as the page numbers.
- HIGH: Clicking the cog next to Home displays the modal ok, however there’s no close icon within the modal. There should be an X to the top right.

Questions about other items:

1) HIGH: Clicking a column heading does not re-order the table.
I can do this, but probably it will be better to organize sorting at the server side?

2) 
HIGH: Within the designs, clicking on a patient record pulls up a side panel showing the patient’s information. It doesn’t direct the user to the Patient Summary directly.
HIGH: Add a ‘View’ column to the table, which launches the users into the patient summary screen. Clicking any other part of the row pulls up the side panel.

OK, but it is opposite to:
click on Row = redirect to Summary
click on View = open details panel
What variant is true?

3) HIGH: The patient summary tab should be blank in MPV view (no labels)
What means at **patient summary tab** ? Content area with panels Allergies, Contacts etc.?
But what should at content area in this case?

**Comment by PhilBarrett** [comment]
@simongamester Any thoughts on this please

**Comment by tony-shannon** [comment]
> HIGH: Clicking a column heading does not re-order the table.
I can do this, but probably it will be better to organize sorting at the server side?

if easy to do please do browser side

> OK, but it is opposite to:
click on Row = redirect to Summary
click on View = open details panel
What variant is true?

Click on Row to open details panel
Click on View to redirect to summary please

> HIGH: The patient summary tab should be blank in MPV view (no labels)
What means at patient summary tab ? Content area with panels Allergies, Contacts etc.?
But what should at content area in this case?

In MPV view, keep the headings very simple on Left Hand side, just have Patients please, nothing else

**Comment by PhilBarrett** [comment]
> HIGH: The font size for input and textarea elements with the forms appears to be too small. Would recommend  font-size: 14px;

Has this been covered already @BogdanScherban

**Comment by kuvakina** [comment]
@PhilBarrett can we close this issue?

**Comment by PhilBarrett** [comment]
> > HIGH: The font size for input and textarea elements with the forms appears to be too small. Would recommend  font-size: 14px;
> 
> Has this been covered already @BogdanScherban

@kuvakina awaiting confirmation on this, then yes can be closed, cheers

**Comment by kuvakina** [comment]
@PhilBarrett this one is done, and with it, we can say that task is done too

**Comment by PhilBarrett** [comment]
Closing as completed
