### ISSUE TITLE
NES - ReSPECT UX/UI Refinements - Medium Priority

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#49]
See link for full report

https://docs.google.com/document/d/1E5-vaRo6b5-E3lkBZIhEZQCP0fYIkLVBi8meNbQ2zrQ/edit#heading=h.96czpxuz6dau

**Comment by PhilBarrett** [comment]
**Multi Patient View**

 - [x] MEDIUM: Table header is missing. Should include:

Cog to change viewable fields
Title
Search icon for filtering

 - [x] MEDIUM: Font sizes for column heading and cells is too small. Also change to HK Grotesk

th {
font-size: 16px;
}

th {
font-size: 15px;
}

 - [x] MEDIUM: Table should be padded within its container. See document for correct spacing:
 - [x] MEDIUM: Show ascending / descending icons next to each column heading.
 -  [ ] MEDIUM: Buttons need a tidy up. Icons should be be vertically aligned to sit within the middle of the button and there should be a larger space between the icon and the text.

**ReSPECT**
 -  [x] MEDIUM: It’s not clear which input element the ‘Street Address’ belongs to. Would suggest adding a larger bottom margin below it:

	margin-bottom: 15px;

 - [x] MEDIUM: Increase the bottom margin on form labels

margin-bottom: 15px;

 - [x] MEDIUM: RIght align the cancel button. It currently appears to be centrally aligned within a padded box:

 - [x] MEDIUM: Breadcrumb trail does not reference the Patient Summary (not referenced in the design). Should read:

Home -> Patient Summary -> ReSPECT

 - [x] MEDIUM: Reduce font weighting for titles within headers. Would recommend:

font-family: HK Grotesk;
font-weight: 400;

 - [x] MEDIUM: When the System Information panel is expanded, the Problems / Diagnosis panel should not be collapsed. Would also recommend that System Information should always be expanded.

**Comment by BogdanScherban** [comment]
These issues have been done:
MEDIUM: It’s not clear which input element the ‘Street Address’ belongs to. Would suggest adding a larger bottom margin below it:
MEDIUM: Increase the bottom margin on form labels
MEDIUM: RIght align the cancel button. It currently appears to be centrally aligned within a padded box:
MEDIUM: Breadcrumb trail does not reference the Patient Summary (not referenced in the design). Should read:
MEDIUM: Reduce font weighting for titles within headers. Would recommend:
MEDIUM: When the System Information panel is expanded, the Problems / Diagnosis panel should not be collapsed. Would also recommend that System Information should always be expanded.

**Comment by kuvakina** [comment]
@PhilBarrett this one is fixed.
