### ISSUE TITLE
Search for existing patient who has a ReSPECT form

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#5]
As a healthcare/care professional I need the 
the ability to search for an existing ReSPECT form for a patient within the application

**Comment by tony-shannon** [comment]
this solution will need to craft its own MPI and so all patients can be expected a respect form

**Comment by PhilBarrett** [comment]
As per
https://projects.invisionapp.com/share/DAQQSTW9WVM#/screens/349350833 &
https://projects.invisionapp.com/share/DAQQSTW9WVM#/screens/349350836

**Comment by ChikongCham** [comment]
Record navigation button labels (previous, next) disappear when using Contrast Mode.
![ReSPECT system UAT - Contrast Mode issue](https://user-images.githubusercontent.com/51081438/58415697-329b1a80-8077-11e9-9a03-795e2da5418d.png)

**Comment by PhilBarrett** [comment]
> Record navigation button labels (previous, next) disappear when using Contrast Mode.
> ![ReSPECT system UAT - Contrast Mode issue](https://user-images.githubusercontent.com/51081438/58415697-329b1a80-8077-11e9-9a03-795e2da5418d.png)

@ChikongCham this would require a separate issue. I understand NES are recording these in their own system if that helps.
