### ISSUE TITLE
NES - ReSPECT UX/UI Refinements - Low Priority

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#50]

**Comment by PhilBarrett** [comment]
**General**
 - [x] LOW: Close button should have greater border radius: 

border-radius: 25px;

- [x] LOW: All boxes should have hard edges, not rounded.

**ReSPECT**
- [x]  LOW: Patient Summary panel should have consistent top and bottom padding. Suggest increasing the top padding to match the bottom.
- [ ] LOW: Panel footers should now have a grey background.
- [x] LOW: Increase the line heights for footnote text to improve legibility. Also increase font size:

font-size: 14px;
line-height: 1.3em;
font-family: HK Grotesk;

 - [x] LOW: Soften the borders on textareas.

border-color: E5E5E5
 - [ ]

**Comment by BogdanScherban** [comment]
These issues have been done:
> LOW: Close button should have greater border radius - for ALL buttons
> LOW: All boxes should have hard edges, not rounded.
> LOW: Patient Summary panel should have consistent top and bottom padding. Suggest increasing the top padding to match the bottom.

@simongamester 
Simon, could you please clarify - what it means?
>  LOW: Increase the line heights for footnote text to improve legibility. Also increase font size:

**Comment by simongamester** [comment]
Sorry Bogdan, I'm not quite sure a I can't get onto nes-ra.ripple to check this. I think this refers to text which appears immediately below input elements. The screen below was taken from my design and shows how footnote text should appear. I think this is different on the latest build. (Note the line spacing the margins above and below the text.)

![Screenshot 2019-04-03 at 12 14 53](https://user-images.githubusercontent.com/8059219/55474883-3e83d680-560a-11e9-8b4c-9b832bcaf31e.png)

**Comment by kuvakina** [comment]
@simongamester could you please specify where is it: 

1. Panel footers should now have a grey background.
2. Soften the borders on textareas.

**Comment by simongamester** [comment]
1. I think this has been resolved. There was a typo on the original document which should have read 'panel footers should *NOT* have a grey background'. I can see that this has been applied.

2. Refers to the border colour of textareas as highlighted below.

![Screenshot 2019-04-19 at 18 22 18](https://user-images.githubusercontent.com/8059219/56435388-21205f00-62d0-11e9-8ea0-9b92573977c7.png)

The border colour should a lighter grey. Recommend setting this to:

border-color: #E5E5E5

**Comment by kuvakina** [comment]
Thanks @simongamester , I understand. Then we will fix 2 issues

**Comment by kuvakina** [comment]
The issues were solved:

LOW: Increase the line heights for footnote text to improve legibility. Also increase font size:
https://www.screencast.com/t/RnJIw4mUw39b

LOW: Soften the borders on textareas:
https://www.screencast.com/t/VVG0qaQuST0s

**Comment by PhilBarrett** [comment]
remaining task split off and put into icebox "Panel footers should now have a grey background." see #93
