### ISSUE TITLE
UI fixes

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#51]
- [x] Removal of Tour function
 - [x] Removal of Footer

**Comment by PhilBarrett** [comment]
![Screen Shot 2019-03-15 at 08.44.17.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206455f66b7191a378e70c2f55415e49be5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5f35aa984ecd5af048e8495ca0113163f43b.png)

**Comment by kuvakina** [comment]
Tour and Footer were hidden from NES app: https://www.screencast.com/t/kwbEeWMk3

(just in case we hid it, not removed)

**Comment by PhilBarrett** [comment]
Tested, working fine. Thank you
