### ISSUE TITLE
NES - ReSPECT Bugs

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#54]

**Comment by PhilBarrett** [comment]
- [x] When navigating to different records I can see the Ivor cox ReSPECT form I previously created in said record.  Presume MPI related?
- [x] Dates show US format (MMDDYY) not UK (DDMMYY)
- [x] section 10 shouldn’t show editing as it’s auto completed
- [x] version warning modal and edit version icons not available
- [x] Previous versions of the ReSPECT form should be read only - current I can edit the previous version
- [x] The status displays as editing/in progress when going into a previous ReSPECT form version
 - [x] No auto logout

**Comment by kuvakina** [comment]
Where is this: 
- Dates show US format (MMDDYY) not UK (DDMMYY)

@BogdanScherban isn't this working:
- Previous versions of the ReSPECT form should be read only - current I can edit the previous version
- The status displays as editing/in progress when going into a previous ReSPECT form version
Video: https://drive.google.com/file/d/1QW6flGZu9PbZbpJXm6A9w5A1x3IE3O_1/view

We have a popup message to Login again:
- No auto logout

This one described in issue #37 
- section 10 shouldn’t show editing as it’s autocompleted

**Comment by BogdanScherban** [comment]
@PhilBarrett @tony-shannon

This was done:
> Dates show US format (MMDDYY) not UK (DDMMYY)
> Previous versions of the ReSPECT form should be read only - current I can edit the previous version
> The status displays as editing/in progress when going into a previous ReSPECT form version

This issue isn't actual more, because we added modal window for error handler:
>  No auto logout

This issue will be done tomorrow, when we create one general button to update version (Publish):
> section 10 shouldn’t show editing as it’s auto completed

**Comment by kuvakina** [comment]
@PhilBarrett @tony-shannon 

The issue with section 10 (shouldn’t show editing as it’s auto completed) was fixed: 
![2019-04-18_1807](https://user-images.githubusercontent.com/40596171/56370998-f0272800-6204-11e9-9c2d-eca8d854b4ed.png)

**Comment by kuvakina** [comment]
@BogdanScherban Please change date also here:

- [ ] Dates show US format (MMDDYY) not UK (DDMMYY)
![date](https://user-images.githubusercontent.com/40596171/56498821-21a53980-650c-11e9-8fd2-f8f5d2501a45.png)

**Comment by PhilBarrett** [comment]
Reviewed and closing
