### ISSUE TITLE
Migrate Qewd Courier (Respect form) endpoint from YottaDB to openEHR API 

### ISSUE THREAD

**Issue by tony-shannon** [RippleOSI/NHS_Ed_Scotland_Open_Platform#57]
AS interim step Rob has developed QewdCourier MS that persists Respect form UI data to  YottaDB 
This is pending the development of a new API type for multiple version forms in openEHR, as Respect form is the first

More details to follow

**Comment by tony-shannon** [comment]
see related repo with current version of Respect form API, persistent to YottaDB backend, done today by @robtweed
https://github.com/QEWD-Courier/QC-ReSPECT-MS
also see within there, current UI to openEHR JSON mapping in /template, which should be key to refactoring to openEHR DB backend

**Comment by tony-shannon** [comment]
FAO Alexey @killmenot who has helped with our Qewd Courier openEHR MS work

**Comment by tony-shannon** [comment]
NB write up of PulseTile UI to Qewd APIs for Respect Form is available here
https://docs.google.com/document/d/1-EXxplkEPG8OckYzx085164_E5_g4DbZS0FQ0dRqZ7c/edit?usp=sharing

**Comment by tony-shannon** [comment]
PS link to mockups which may give helpful UI context here
https://invis.io/JZQNPCFTK2S

**Comment by tony-shannon** [comment]
Link to related openEHR template and write up from @freshehr here
https://github.com/RippleOSI/Ripple-openEHR/blob/master/docs/bindings/Current%20Ripple%20Headings/NSS%20ReSPECT/NSS_RESPECT.md

**Comment by tony-shannon** [comment]
and more notes on the mapping effort by @DmitrySolyannik between PulseTile and openEHR JSON here
https://docs.google.com/spreadsheets/d/1shKr1D7YSGvd3L8km56BdBxhe7hVQMVpkBBkCQY7T08/edit?usp=sharing

**Comment by tony-shannon** [comment]
Update by email between @killmenot and @BogdanScherban 

> Hi Bogdan,
> 
> I've updated my version of code but there are some problems with mapping logic + I have some questions for teammates. I need a couple of days to resolve these issues.
> In the meantime, you can work with this version of the code:
> https://github.com/killmenot/QEWD-Courier/tree/develop-respectforms
> Please ask @Dmitry to help you with deploy if you haven't done it yet.
> 
> 1. GET /api/patients/:patientId/respectforms
> Sample of data returned: https://gist.github.com/killmenot/32bb81ddf68256341529e06864d11a12
> NOTES: 
>  - "status" prop's value seems incorrect. I'll fix it soon.
> 
> 2. GET /api/patients/:patientId/respectforms/:sourceId/:version
> Sample of data returned: https://gist.github.com/killmenot/1c5e77b2f37a997094190b090d9a2144
> NOTES:
>  -  Please ignore "status" and "dateCompleted" props in nested objects. They are hardcoded now
>  -  Some of props (such as "summaryInformation", "personalPreferences", etc...) can be undefined because when a form version can be created without any props (I'll clarify this moment).
> 
> 3. POST /api/patients/:patientId/respectforms
> You can skip passing data here but if you need to pass anything to API, it expects "data.respect_form" from (2) above
> NOTES:
>  - Currently, it doesn't return correct response by spec:
> https://docs.google.com/document/d/1-EXxplkEPG8OckYzx085164_E5_g4DbZS0FQ0dRqZ7c/edit
> 
> 4. Please note that "emergencyContacts.contactsArray", "confirmation.confirmationsArray", "clinicalSignatures.signaturesArray" can contain and should return multiple items
> 
> 5. clinicalRecommendation.cprValue can be "CPRRecommended", "NotforCPR", "ModifiedCPR" or "N/A" 
> 6. capacityAndRepresentation.legalProxyValue can be "Yes", "No", "Unknown" and "N/A"
> 7. involvement.involvementValue can be "valueSetA", "valueSetB", "valueSetC1", "valueSetC1", "valueSetC2", "valueSetC3", "valueSetD"
> Note: I can update "N/A" to any value you need. it's a value by default if no code match (@Tony  - ???)
> 
> @ALL
> Tomorrow, I will ask questions I have about respectforms logic and methods and continue with POST/PUT methods. Unit tests for respectforms logic are currently disabled or haven't written but I will take care about them on Wednesday
> 
> 
> 
> On Tue, Apr 9, 2019 at 2:03 PM Alexey Kucherenko  wrote:
> P.S.
> develop+respectforms (db version) merged here
> https://github.com/killmenot/QEWD-Courier/tree/develop-respectforms
> so I will work with this branch and then reopen PR
>

**Comment by PhilBarrett** [comment]
@killmenot can you confirm the migration is now complete please?

**Comment by killmenot** [comment]
@PhilBarrett I talked with Dmitry regarding additional changes and he has nothing to add to the opened PR. He and Bogdan works with that version.

The only changes we need to take care are:
 - apply db fix to YottaDB keys length (I saw a separate ticket)
 - unit tests that covers mapping to PT JSON and vice versa (will do it in a separate PR)

**Comment by PhilBarrett** [comment]
Thanks for the update, closing here
