### ISSUE TITLE
PDFkit problems

### ISSUE THREAD

**Issue by BogdanScherban** [RippleOSI/NHS_Ed_Scotland_Open_Platform#58]
@simongamester 

Hi, Simon! 
I totally added PDF kit to NES. Data from ReSPRECT forms is displayed in PDF. But I found few moments, where I need in your help.

1) Section 4, parameter "cprValue" (for CPR recommendations):
![image](https://user-images.githubusercontent.com/39263134/55335394-b08ddb80-54a3-11e9-9dcd-c6c3dafd1c0a.png)
Right block is usually red. Even if we don't select it. Probably, the reason in page1 image.

2) Text isn't wrapped in:
Section 1 - address
Section 2 - summary and details
and in all other textareas

I read in PDFkit, that text should be wrapped automatically. But, unfortunately, we usually have long single row:
![image](https://user-images.githubusercontent.com/39263134/55335673-3c076c80-54a4-11e9-9f3f-93b725258452.png)

All other is norm. Could you please help me with these two moments?

**Comment by simongamester** [comment]
1. Sorry @BogdanScherban, not quite sure what you mean here. Are you referring to the border of the "CPR attempts NOT recommended" box in the bottom right of your screen? Or the X when 'Focus on symptom control" is selected?

2. This was working correctly in my repo, see screen below:

![Screenshot 2019-04-01 at 18 18 20](https://user-images.githubusercontent.com/8059219/55346498-8e4b8c00-54aa-11e9-93f1-a3fcaed3a9d9.png)

Can you check that the width attribute is set for the following part:

![Screenshot 2019-04-01 at 18 19 08](https://user-images.githubusercontent.com/8059219/55346579-bdfa9400-54aa-11e9-838d-38a6f515bd30.png)

Line breaks should be set by default to automatically wrap within the designed width of the text box (if provided) or the page margin. I'm wondering if this this now the default on your version of PDFKit?Try adding the following lineBreak option to this section to see if it changes:

```
    // Diagnostics...
    doc.lineGap(0)
    .text(form.sectionTwoDiagnostics, 31, 208, {
      width: 553,
      height: 58,
      lineBreak: true
    });

    // Details...
    doc.text(form.sectionTwoDetails, 31, 300, {
      width: 553,
      height: 36,
      lineBreak: true
    });
```

As a last ditch attempt, try reducing the width to see if we can force line breaks at all. Maybe width: 200 ?

Simon

**Comment by BogdanScherban** [comment]
@simongamester 
Thanks, Simon. Look:

About my first question - this square is always red. Probably, it is because this square is red in initial picture (before we encoded it).
Could you check it?
![image](https://user-images.githubusercontent.com/39263134/55395617-8e9b6400-554a-11e9-8b8f-248f3218ac95.png)

Besides this, I don't see the code, which should add red square in demo:
http://wrathful-request.surge.sh/browser.html

About second question. Probably, '@react-pdf/pdfkit' doesn't have text wrapper. I tried to check this functionality in library, but I haven't found it. For this reason I realized text wrapping manually.

**Comment by simongamester** [comment]
Hi @BogdanScherban 

1. Yes, you're right. The red box is part of the image we import into the PDF, so should always remain red.

2. I've taken a look at the source code for the react library too and can't see reference to the TextWrapper class which is found within the standard pdfkit library. Is it possible this references a older version? Or would it possible to import the lineWrapper class to get this working.

Alternatively, would this work?

https://github.com/ducret201/react-pdfkit

I'm assuming this is just a wrapped for the original PDFKit? So might be possible to use this instead to pull in the lineWrapper functionality?

**Comment by kuvakina** [comment]
While testing PDFKit, found the next issues:

- [x] That's how PDF opens in a new tab in **Chrome**:  https://www.screencast.com/t/tDGSNVbI (but it works ok in **Firefox**: https://www.screencast.com/t/sKwJgoOvW )

- [x] In **Section 3** scroll not working (I chose right balance https://www.screencast.com/t/Auq5nQ9UtyF ) https://www.screencast.com/t/JvQf30XXX8I 

- [x] In **Section 4** results of radio buttons not showed (I choose "CPR attempts recommended") https://www.screencast.com/t/SxO9zABmiQlb
- [x] In **Section 5** chosen answers not shown (should be should Yes/Yes) https://www.screencast.com/t/toUEDAOJer3 
- [x] In **Section 6** A, B, C, D chosen answers not shown (same when I chose A or D) https://www.screencast.com/t/XnUNmRgGo42
- [x] In **Section 7** when creating the second version, answers overlap https://www.screencast.com/t/UFvUJVIyLG8
- [x] In **Section 7** signature not added https://www.screencast.com/t/bJpHaajca
- [x] In **Section 8** Other details not added https://www.screencast.com/t/4xBMOFgRIr (in the form: https://www.screencast.com/t/8ZIwbyhTJoZ )
- [x] In **Section 9** signature not added https://www.screencast.com/t/vAM2UPSDfW8p

**Comment by simongamester** [comment]
Regarding the PDF bug in Chrome. Web Inspector shows this as a 404 error with content-type: text-html

![Screenshot 2019-04-18 at 17 00 15](https://user-images.githubusercontent.com/8059219/56374616-86eee700-61fb-11e9-8454-23b43aeab68d.png)

This is the second of two requests from the same url. The first is for content-type: application/pdf. Could it be that this being forwarded or rewritten by the web server, then dropping the content-type?

Alternatively, what would happen if the PDF were returned as an attachment with content-disposition:

content-disposition "attachment; filename=respectPDF"

This would download to the users browser instead of displaying as a preview, but may be a quick workaround if there's a browser issue.

**Comment by kuvakina** [comment]
@simongamester but for some reason, it works correctly in Firefox, so I assume it is a browser issue

**Comment by simongamester** [comment]
Yes, but might be the way different browsers handle binary streams. Maybe Firefox defaults to PDF, but Chrome requires it to be more specific. In the demo version I handed over to Bogdan, the PDFs were displaying OK in Chrome and Firefox.

**Comment by simongamester** [comment]
I've looked through the earlier issues on the PDF and have updated my original demo version to resolve the issues. @Bogdan, if you take a look at the following DIFF you should be able to make the same incremental changes to your version. 

https://github.com/foliojs/pdfkit/commit/71eee9285af40feb08d3032f085644ba25250344#diff-a78f49ab1342965a5530cd86ac39c7cc

Below are some notes in each issue individually:

Chrome compatibility - see my earlier comment with suggestions.

Section 3 - Not looked into this, however I can’t replicate this issue on the demo.

Section 4 - I’ve added a new function to the demo called getCPRValue and created a new signature text box to display the clinician signature. getCPRValue returns the X coordinate where the signature should appear i.e. left, middle or right of the page.

Section 5- I think capacityFirst data has changed over my demo version. Originally we were expecting integers 1 = Yes, 2 = No however the data has changed to true and false boolean values. I’ve updated the case statement within the code to circle the appropriate response. For legal proxy, the JSON values and names have changed. CapacitySecond is now called LegalProxyValue. Values have changed and from integers as above to strings: Yes, No, Unknown.

Section 6 - involvement.variant has changed to involvement.involvementValue. Values have also changed i.e. ‘variantA’ -> ‘valueSetA’. Now updated.

Section 7 - Unable to replicate this on I’m afraid. In the demo we loop through each object in clinicalSignatures.signaturesArray to order them, taking out senior clinicians as they appear in the third row on in the table. Each of the three rows is allocated a separate set of text boxes based on this. Can you provide the JSON for the example in your screenshot?

Section 8 - Other Details appears to be missing from the latest json (see emergencyContacts.contactsArray. There a details field in emergencyContacts.details, but I think this is being moved into the contactsArray. I’ve therefore updated the demo to check for this, so when the JSON is changed, this should work again.

Section 9 - We left out signatures in the demo, however new text boxes for this have now been added.

**Comment by kuvakina** [comment]
@simongamester I've marked issues that were solved above. And the main one is that PDFKit didn't open in Chrome.

However some issues left. Some ofthen fron backend. I believe Dmitry raised this issue.

**Comment by simongamester** [comment]
@kuvakina Just looked through these. Is there anything you need me to look at here or are the other sections yet to be completed?

**Comment by kuvakina** [comment]
Hi @simongamester sorry didn't update yet: we solved the issue with Chrome, thanks. 

The issue left is with Section 4 - CPR recommendation: we don't see a chosen answer on PDF form. Could you please help us?

**Comment by simongamester** [comment]
The radio box on the form determines where the signature should be displayed at the bottom of the page. I've created a function in my demo called getCPRValue which takes obj.clinicalRecommendation.cprValue and returns an X coordinate where the signature (obj.clinicalRecommendation.clinicalSignature) should be displayed i.e. 'CPRRecommended', 'ModifiedCPR', 'NotforCPR'
