### ISSUE TITLE
Searching error - Response code

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#59]
When a user searches for a patient and enters a wrong value, an error message appears. The error message response code isn't accurate and needs to change from the MPI server to reflect correct error response code

![image_2019_04_12T10_52_20_289Z.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46e1999b2487bcfbdfb8e67cf409cfc57b7276231651f11422d5dc7ae71b4143434d0eee1e020a17b8eb8339a3e46d23df5f0ebbd63f0c25c36911acb1814ab602ef768e5d99a4fedb1294b7607caddecd5d340c041083fe5830a5994dce5df74ee14b5db65e.png)
![image_2019_04_12T10_53_25_725Z.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46e1999b2487bcfbdfb8e67cf409cfc57b7276231651f01422d0dc7fed174143434d0eee1e020a17b8eb8339a3e46d23df5f0ebbd63f0c25c36911acb1814ab602ef768e5d99a4fedb1294b7607caddecd5d340c041083fe5830a5994dce5df74ee04c57b65e.png)

**Comment by PhilBarrett** [comment]
Need to understand if the issues experienced is React Admin related

**Comment by kuvakina** [comment]
The issue with search was solved:
![2019-04-23_2021](https://user-images.githubusercontent.com/40596171/56602367-fa329780-6605-11e9-9f1e-0096361fe1e6.png)

@PhilBarrett

**Comment by PhilBarrett** [comment]
Reviewed and closing
