### ISSUE TITLE
Edit/Update ReSPECT form

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#6]
As a healthcare/care professional I need the ability to edit / update a ReSPECT form within the application

https://www.respectprocess.org.uk/_pdfs/ReSPECT-Specimen-Form.pdf

**Comment by tony-shannon** [comment]
? if we have 1 /3/9 sections in the frontend?
do we have 1/3/9 API calls to make
can React keep state of null values for incomplete forms (eg 90 data points over 9 sections, 12 filled in , so 78 null,)

**Comment by tony-shannon** [comment]
Q for Simon
Can we trigger conditional rules after section started?

**Comment by PhilBarrett** [comment]
@BogdanScherban please can you make  list of the changes you're making, following your call on last week. Please can you also post a latest sample of JSON that you have for @tony-shannon

**Comment by tony-shannon** [comment]
done with long tails of issues being tackled now
