### ISSUE TITLE
Creating new patient requires refresh before appears

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#60]
Added new patient and yet row empty just after, needed to refresh a few times

**Comment by PhilBarrett** [comment]
![Screen Shot 2019-04-18 at 10 43 29](https://user-images.githubusercontent.com/12699244/56352362-057d6180-61c7-11e9-86ed-b7fffa38687e.png)

**Comment by PhilBarrett** [comment]
Now receiving new error related to MPI

![Screen Shot 2019-04-18 at 15 55 21](https://user-images.githubusercontent.com/12699244/56371618-54da8680-61f5-11e9-865f-0e2491dc8f45.png)
![Screen Shot 2019-04-18 at 15 58 54](https://user-images.githubusercontent.com/12699244/56371620-54da8680-61f5-11e9-9ee6-be789c060d46.png)
![Screen Shot 2019-04-18 at 16 14 09](https://user-images.githubusercontent.com/12699244/56371622-54da8680-61f5-11e9-8cd1-04a42b28189c.png)

**Comment by kuvakina** [comment]
Now when you create a new patient you see it immediately as the last row.
