### ISSUE TITLE
Patient Banner issues

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#61]
- [x] Patient Banner - DOB invalid, 
- [x] PatientBanner - Doctor, NA so remove from Banner
- [ ] Patient information disappears sporadically

**Comment by PhilBarrett** [comment]
![Screen Shot 2019-04-18 at 10 47 07](https://user-images.githubusercontent.com/12699244/56352586-76bd1480-61c7-11e9-90e5-d4df8e9f3745.png)
![Screen Shot 2019-04-18 at 09 16 26](https://user-images.githubusercontent.com/12699244/56352624-83da0380-61c7-11e9-81fb-3726bc19352a.png)

**Comment by kuvakina** [comment]
@PhilBarrett @tony-shannon 
Bogdan fixed this issue.
tested DOB and Doctor, NA : https://www.screencast.com/t/TYDGfHYs
Didn't see the disappearance of  Patient information also

**Comment by PhilBarrett** [comment]
Unable to recreate "Patient information disappears sporadically" issue. Closing
