### ISSUE TITLE
New form created - displays sections already as completed

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#63]
New patient + New version
Section 1 & 2 showing as complete on arrival

**Comment by PhilBarrett** [comment]
![Screen Shot 2019-04-18 at 10 51 10](https://user-images.githubusercontent.com/12699244/56352810-e9c68b00-61c7-11e9-81e4-1f5c175800da.png)

**Comment by kuvakina** [comment]
This issue was done for new version:
https://www.screencast.com/t/SwoYRtJOn

But @PhilBarrett how we should highlight a new patient? (all sections already white):
https://www.screencast.com/t/8RFe9Cbc5Xx
