### ISSUE TITLE
Change in logic when new version published

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#64]
When the user clicks publish a model displaying either successfully published, or error message (detailing the error) is required

Once model acknowledged it needs to take you back to the list of respect versions

**Comment by tony-shannon** [comment]
Bogdan has improved this and now redirects to updated list of versions

**Comment by kuvakina** [comment]
Bogdan made it that when the version was successfully published, we are redirected to versions list.

Bogdan added error message, when version not saved, but for now I can't test it.
