### ISSUE TITLE
Ensure sections 4 and 6 are mandatory before a publish option appears

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#66]

**Comment by PhilBarrett** [comment]
![Screen Shot 2019-04-18 at 10 57 10](https://user-images.githubusercontent.com/12699244/56353172-bdf7d500-61c8-11e9-8995-95c8d72bff05.png)

**Comment by PhilBarrett** [comment]
Section 4 saving with invalid date

**Comment by kuvakina** [comment]
This issue was solved: https://www.screencast.com/t/nb6RnTQSeUhr

**Comment by PhilBarrett** [comment]
@kuvakina can you confirm that when creating a new form, or updating an existing form (a new version) that section 4 and section 6 must be completed before it can be published?

**Comment by PhilBarrett** [comment]
Tested and confirmed
