### ISSUE TITLE
Mismatch between Completed Sections and returned data

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#68]
![Screen Shot 2019-04-18 at 10 59 07](https://user-images.githubusercontent.com/12699244/56353332-10d18c80-61c9-11e9-9e50-9af44694176d.png)
![Screen Shot 2019-04-18 at 10 59 26](https://user-images.githubusercontent.com/12699244/56353333-116a2300-61c9-11e9-8ea9-fd68f24c761d.png)

**Comment by BogdanScherban** [comment]
@PhilBarrett 
Is it OK?
![image](https://user-images.githubusercontent.com/39263134/56423079-20c59b00-62b3-11e9-92d6-374517fe7cb1.png)

I think, main theme color will be better than light blue color

**Comment by PhilBarrett** [comment]
@BogdanScherban that's fine, thanks. I note C is always highlighted in the right hand side, not greyed out as the others, any reason for this?

**Comment by PhilBarrett** [comment]
Remaining and separate issue created as #94
