### ISSUE TITLE
Versions not saving

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#69]

**Comment by PhilBarrett** [comment]
Nothing saved
![Screen Shot 2019-04-18 at 11 13 04](https://user-images.githubusercontent.com/12699244/56354171-fe585280-61ca-11e9-8677-be167604da24.png)

![Screen Shot 2019-04-18 at 11 13 10](https://user-images.githubusercontent.com/12699244/56354172-fe585280-61ca-11e9-9ad3-b76c730247b8.png)

**Comment by tony-shannon** [comment]
Section 3 - slider not saving

**Comment by tony-shannon** [comment]
Section 4 - slider, CPR rec, date completed not saving (Clin Guidance is)

**Comment by tony-shannon** [comment]
Section 5 isnt saving either value

**Comment by tony-shannon** [comment]
Section 6 radio buttons not saving

**Comment by tony-shannon** [comment]
Section 7, 8, 9 not saving

**Comment by tony-shannon** [comment]
Publish not working - waiting for success/failure response

**Comment by kuvakina** [comment]
@tony-shannon some issue were fixed and I added the ones I've noticed:

- [x] Section 2 - "Details of other relevant planning documents" not saving
- [x] Section 3 - slider not saving
- [x] Section 4 - slider
- [x] Section 4 - CPR rec
- [ ] Section 4 - date completed not saving (Clin Guidance is)
- [x] Section 4 - Clinical signature not saving
- [x] Section 5 - isnt saving either value
- [x] Section 6 - radio buttons not saving
- [x] Section 6 - D not saving
- [ ] Section 6 - "Record date, ..." not saving
- [x] Section 7 - not saving
- [x] Section 8 - not saving
- [x] Section 9 - not saving
- [ ] All sections - Date completed come from server as dafault even after saving
- [x] Publish not working - waiting for success/failure response

**Comment by PhilBarrett** [comment]
This has been picked up by splitting the issues out. Closing here
