### ISSUE TITLE
Clicking onto Home button in the breadcrumb trail takes to MPV + previous search (plus null result), click on x in search box and takes back to home screen

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#73]
Similar behaviour to #71

**Comment by kuvakina** [comment]
@PhilBarrett could you please add video? 
I don't see X in search box  when I click Home button

**Comment by kuvakina** [comment]
@PhilBarrett This issue was solved:
https://drive.google.com/file/d/12DK8fHHLGWh9TkZ3f4N0feX3Ygr99_V7/view

**Comment by PhilBarrett** [comment]
Reviewed and happy to close, thanks
