### ISSUE TITLE
Bug with Versions# after 11th version

### ISSUE THREAD

**Issue by kuvakina** [RippleOSI/NHS_Ed_Scotland_Open_Platform#76]
Found a problem: 
When a user had created versions with a number more than 11, versions counter at the server side returns to 1
![image](https://user-images.githubusercontent.com/40596171/56377555-5024cb00-6213-11e9-85c9-57e0ee1c31f3.png)

**Comment by kuvakina** [comment]
This issue was solved: https://www.screencast.com/t/BLBVnpWjw5

**Comment by PhilBarrett** [comment]
Before closing this issue, what was the reason for the bug please @kuvakina

**Comment by kuvakina** [comment]
the reason for a bug was in versions counter on the server side: counter was set up by default on 11. Bogdan and Dima changed it.
