### ISSUE TITLE
Reduce main NHS Scotland logo on landing screen

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#77]
Please reduce by 30-40%

**Comment by PhilBarrett** [comment]
![Screen Shot 2019-04-18 at 18 10 38](https://user-images.githubusercontent.com/12699244/56378601-704d8d80-6205-11e9-9848-2a5024113eb3.png)

**Comment by kuvakina** [comment]
We changed this. Now it looks this way:
![Screen Shot 2019-04-19 at 16 11 49](https://user-images.githubusercontent.com/40596171/56425724-368c8d80-62be-11e9-9bbf-1d72897c89f1.png)

**Comment by PhilBarrett** [comment]
Thanks, closing off
