### ISSUE TITLE
Change NHS number to CHI Number throughout

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#78]
NES use the CHI number, the platform currently shows NHS Number at

Multi Patient View
Create patient
Single patient view

Needs to be changed to CHI number

**Comment by kuvakina** [comment]
For Multi Patient View , Create patient , Single patient view NHS Number was changed on CHI number. 

This task is Done.

**Comment by PhilBarrett** [comment]
Reviewed and confirmed.
