### ISSUE TITLE
Responsive view brings back old patient banner

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#81]

**Comment by PhilBarrett** [comment]
![Screen Shot 2019-04-24 at 11.15.35.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77276456f76b7191a379ee0c2a54415c4bbe5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c3daa984ecd5ef74ae54457ac103760f43b.png)

**Comment by BogdanScherban** [comment]
@PhilBarrett @kuvakina 
This issue were done

**Comment by PhilBarrett** [comment]
Closing after review
