### ISSUE TITLE
ReSPECT form spelling errors

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#84]
@kuvakina please can you proof read the ReSPECT form and the application for spelling ,mistakes. I've found a number below

**Section 2** 
-  recomendations recorder **changed to** recommendations recorded
**Section 4** 
- Clinical recomendations **changed to** Clinical recommendations
-  clinicaly **changed to** Clinically
-  includingbeing **changed to**  including being
**Section 5** 
- Do that **changed to** Do they
**Section 6** 
- Do that have legal proxy (e.g. welfare attorney, person with parental responsibility who can participate on their behalf in making recommendations? **changed to** The clinician(s) signing this plan is/are confirming that (select A,B or C, OR complete section D below):
- They have benn **changed to** they have been
- **REMOVE** Including diagnosis, communication needs (e.g. interpreter, communication aids) and reasons for the preferences and recomendations recorder.

**Comment by BogdanScherban** [comment]
@kuvakina @PhilBarrett 
All issues were done.

**Comment by PhilBarrett** [comment]
Section 7 - Clinician name and clinician signature not clinical
