### ISSUE TITLE
Preferred name not recorded

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#87]
When a PDF is created from the ReSPECT form, the preferred name (e.g. Phil rather than Philip)  is mapped to Prefix (e.g. Mr/Mrs/Dr). I don't see Preferred name as an option in the MPI / UI, to be able to record the patients preferred name.

**Comment by PhilBarrett** [comment]
![Screen Shot 2019-04-25 at 12.34.57.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77276456f66b7191a379ed0c2855415a49be5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecd5ef742e34c54a1133161f43b.png)

![Screen Shot 2019-04-25 at 12.35.19.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77276456f66b7191a379ed0c2854415e47be5d4a1f06a3a3dc78e2a436628f0e5abe846e5a22c16f42fdbdd61fbf08b975824cd0e0b99850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecd5ef742e34c56a01a3664f43b.png)

**Comment by kuvakina** [comment]
@PhilBarrett 
This issue was fixed:
![PN1](https://user-images.githubusercontent.com/40596171/56735858-5107b080-676f-11e9-8569-e588993a7d09.png)
![PN2](https://user-images.githubusercontent.com/40596171/56735870-582ebe80-676f-11e9-921f-e98a3564c661.png)

**Comment by PhilBarrett** [comment]
Reviewed and resolved.
