### ISSUE TITLE
NES Patient and Version fixes

### ISSUE THREAD

**Issue by kuvakina** [RippleOSI/NHS_Ed_Scotland_Open_Platform#88]

**Comment by kuvakina** [comment]
- [x] Hide Prefered Name (old Prefix) from Patients List

![2q](https://user-images.githubusercontent.com/40596171/56749838-2c213680-678b-11e9-872b-9a8f43cf49dd.png)

- [x] Section 7 - Clinician name and clinician signature, not clinical ( #84 )

- [x] Section 4 - slider - needs to be a binary choice: 0 all the way to the left OR 100 all the way to the right  (#80 )

- [x] Sometimes have an error when saving the first version:

**Either this**: 
```
error: "#1.0.0 Invocation exception to method:update:com.ethercis.validation.wrappers.ValidationException: Validation error at /content[openEHR-EHR-SECTION.respect_headings.v0]/items[at0006]/items[openEHR-EHR-EVALUATION.care_preference_uk.v0]/data[at0001]/items[at0039], value is not within interval, expected:1 <= 0 <= 100 "
path: "/api/patients/:patientId/respectforms/:sourceId/:version"
```
**Or this**:
```
error: "No existing respectforms record found for sourceId: ethercis-b8fa67cc-d319-42f6-90ab-ee744d5ea613 and version: 1"
path: "/api/patients/:patientId/respectforms/:sourceId/:version"
```

- [x] Update the version requires to refresh the page

- [x] Create new patient: fix styles
![fix_styles](https://user-images.githubusercontent.com/40596171/56750757-24fb2800-678d-11e9-8016-ddcb2495ca1e.png)

- [ ] Section 7 - save only changes from the first version

- [x] PDFKit: Section 6 - answer D don't shown in pdf
![D](https://user-images.githubusercontent.com/40596171/56751704-5f65c480-678f-11e9-9ae4-c5cdc3dc6fb1.png)

- [ ] Check paginator on Patients List (Seems it shows only 10 users per page, and hide others)

**Comment by DmitrySolyannik** [comment]
@tony-shannon, @PhilBarrett 
This issue fixed in this PR. After merging will output data from step#7
https://github.com/QEWD-Courier/QEWD-Courier/pull/74

**Comment by PhilBarrett** [comment]
" Check paginator on Patients List (Seems it shows only 10 users per page, and hide others)" Created in separate issue in icebox #109

**Comment by PhilBarrett** [comment]
Reviewed and resolved.
