### ISSUE TITLE
When first ReSPECT form is created, two versions are created

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#91]
Version one is the Post
Version two is the GET and Update

**Comment by PhilBarrett** [comment]
Rename author to System

**Comment by kuvakina** [comment]
@PhilBarrett you mean here:
![1111111111111111.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/23a84877-91ff-421f-89b1-9aa088116875)

**Comment by PhilBarrett** [comment]
I mean Dr Jonty Shannon renamed as System

**Comment by PhilBarrett** [comment]
Reviewed and working fine now.
