### ISSUE TITLE
Section 6 option C shows as highlighted bold compared to the other options which are grey

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#94]
![image.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/c10b4a6c-ad0f-4e8a-bf0d-6c21fb4f1793)

**Comment by BogdanScherban** [comment]
The issue has been done and uploaded

**Comment by kuvakina** [comment]
This issue was solved:
![2222222222222.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/b62b14c3-9ca5-441f-bdd0-14fc3c2803fd)
