### ISSUE TITLE
When searching returns no results, I'm unable to create a new record

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#96]
When I search for a patient record, if there are no results returned, it asks me to try again. If i close the modal, it returns me to the home screen. 

I don't have an option to create a new patient record if no results returned.

![Screen Shot 2019-04-30 at 11.31.36.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/a39119f3-a7a2-4a0c-88c1-069a88c79f4d)

**Comment by PhilBarrett** [comment]
Suggestion would be to  do away with the modal and just show 'no results' found in the MPV view 1st row. The Create button is already there.

**Comment by kuvakina** [comment]
@PhilBarrett 
This issue was fixed:
![4444444.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/deaf477d-9884-461e-af79-1b48075d8bb1)

**Comment by PhilBarrett** [comment]
Reviewed and working as intended now, thank you.
