### ISSUE TITLE
Creation of new patient depends on date picker rather than manual DOB

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/NHS_Ed_Scotland_Open_Platform#97]
If I enter numerical values into the new patient record, i get the following error. When I use the date picker this doesn't occur. Need to cater for both manually entering DOB and using the date picker.

![Screen Shot 2019-04-30 at 12.07.22.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/139077fb-b2f0-4824-ac6c-ca540b14464a)

**Comment by kuvakina** [comment]
This issue was solved. Now we can type the date manually and the error doesn't appear:
https://drive.google.com/file/d/1HwDUKPNdMsvb41pS2AnQz4SRaxJfeMMW/view

**Comment by PhilBarrett** [comment]
Confirmed, working fine, thank you
